# Generated by Django 2.2.5 on 2019-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
    ]
