# Generated by Django 2.2.5 on 2019-10-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='post.png', upload_to='post_images'),
        ),
    ]
